Added grayscale image support in put_image_data and exposed image_smoothing_enabled attribute
jupyter-widgets-contrib/ipycanvas pull request #348
Opened 2024-05-13 20:23 UTC by AnyaPorter

In setting up ipycanvas to use in a long-term project I had a couple of options that I think could be beneficial to others.

1. I added grayscale image support in put_image_data so you can now pass in a 2D numpy array instead of being limited to 3D for rgb or rgba (closes #346)
2. I added image_smoothing_enabled to echo the Web Canvas API imageSmoothingEnabled, which is supported in all browser types as per the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled). This allows users to have a similar result to PIL's RESAMPLING.NEAREST when enlarging an image as opposed to the automatic smoothing that occurs now. 

Its my first time working directly with TypeScript/JavaScript so happy to have feedback on a better/preferred way to do what I did and especially on how to test it as I was not sure how to get it to use the forked version aside from installing directly from the github fork. I am happy to update as needed.

2024-05-14 09:20 UTC, martinRenou requested changes
Thanks! I have a couple of suggestions

2024-05-14 09:20 UTC, martinRenou commented on ipycanvas/canvas.py
> +    image_smoothing_enabled = Enum([True, False], default_value=True)
This can be defined as bool:

```suggestion
    image_smoothing_enabled = Bool(True)
```

2024-05-14 09:20 UTC, martinRenou commented on ipycanvas/canvas.py
> +                value = str(value)
I believe we don't need this? The Python boolean will automatically be converted to a JavaScript boolean.

```suggestion
```

2024-05-14 09:20 UTC, martinRenou commented on src/widget.ts
> +    }
In combination with my other suggestion, this should not be needed:

```suggestion
```

2024-05-15 15:18 UTC, AnyaPorter commented
Thanks for the comments! Updated as per your suggestions.

2024-09-04 06:37 UTC, martinRenou approved these changes
Thanks! Sorry for the delay

2024-09-04 08:20 UTC, closed without merging